### ISSUE TITLE
broken image in offer view map

### ISSUE THREAD

**Issue by peter-gerhard** [neeedo/neeedo-webapp#14]
![screenshot1](https://cloud.githubusercontent.com/assets/4236201/8825216/a2f65036-307d-11e5-9347-e1c698034705.png)

in http://www.neeedo.com/offers/view/offerId/ca776143-a0d8-4ee2-825a-96d17e4032b8
chrome

**Comment by sasfeld** [comment]
fixed by 5939dc57cd2f2aac90afde2ced960e592e7393d4
