### ISSUE TITLE
Google Play App icon click does not do anything

### ISSUE THREAD

**Issue by peter-gerhard** [neeedo/neeedo-webapp#17]
http://www.neeedo.com/

after "Wir arbeiten hart an der Umsetzung unsere Mobile App. Einen Prototyp können Sie hier am Stand bereits betrachten"

**Comment by sasfeld** [comment]
Link to Google Play Store

**Comment by sasfeld** [comment]
closed by c55a783be1beb21569c4bc8df4a03d148b59ad82
