### ISSUE TITLE
create offer form is hard to use

### ISSUE THREAD

**Issue by peter-gerhard** [neeedo/neeedo-webapp#22]
- [x] it does not really look like a form, especially the input fields
- [x] when I enter the name what I want to offer like "a damaged iphone" then it creates tags for it, I would have suspected a title which is kept untouched
- [ ] I get the error message "Please enter at least one tag" but there are already tags present
- [ ] the text choose "use current location" should be right of the checkbox
- [ ] clicking on the text "use current location" does not switch the state of the checkbox
- [x] type in you address is not editable, but still present (checkbox is checked)
- [ ] image upload is slow?
- [ ] image upload: the frame suggests that one can see the uploaded image
- [x] image upload feedback (size, formats) does not look nice and is too small
- [ ] submit failed and I am back at the register page

**Comment by sasfeld** [comment]
Regarding "when I enter the name what I want to offer like "a damaged iphone" then it creates tags for it, I would have suspected a title which is kept untouched"  - we had a title two / three weeks ago and clarified that we will fall back to tags (in our whole Tuesday meeting, whole team decision) -> we will improve the placeholder here to lead the user

**Comment by sasfeld** [comment]
@peter-gerhard  What browser did you use?

**Comment by sasfeld** [comment]
@rennersebastian  will work on layout + design
- [x] it does not really look like a form, especially the input fields
- [x] adjust placeholders to look like placeholders
- [x] design fixes

**Comment by sasfeld** [comment]
@peter-gerhard we can't reproduce any of your bugs. Please provide more info and open separate bug tickets if you can reproduce.

**Comment by peter-gerhard** [comment]
@sasfeld  chrome

**Comment by peter-gerhard** [comment]
@sasfeld 

> I get the error message "Please enter at least one tag" but there are already tags present

The "Please enter at least one tag" was present before but it doesn't disappear when I enter a tag

**Comment by peter-gerhard** [comment]
@sasfeld 

> submit failed and I am back at the register page

see #27

**Comment by sasfeld** [comment]
closed, session timeout was increased
