### ISSUE TITLE
address auto completion yields weird suggestions

### ISSUE THREAD

**Issue by peter-gerhard** [neeedo/neeedo-webapp#24]
![screen shot 2015-07-22 at 14 52 58](https://cloud.githubusercontent.com/assets/4236201/8825718/70dd16bc-3081-11e5-8d0b-0d2dda801b06.png)
- maybe restrict it to Berlin?

**Comment by sasfeld** [comment]
Restricting to Berlin: no, that's not a solution.

http://nominatim.openstreetmap.org/search?q=Landsberger&format=json - our geocodng provider only sends one string. We can'T find any quick solution for better usabilty here. 

In the future, we should think of switching the geocodng provider.
