### ISSUE TITLE
Maximum Price of 500 Euro in offer form

### ISSUE THREAD

**Issue by MeiSign** [neeedo/neeedo-webapp#31]
When I try to create my offer the price is limited to 500 Euro.
Displayed error message in the form is: "The maximum allowed price is 500 €"

**Comment by sasfeld** [comment]
As reviewed, we want allow more than 500 €. I set a new limited to exclude unrealistic prices.

**Comment by sasfeld** [comment]
Closed by 5261d0e761032f30ec4af820e4860b4394eda752
