### ISSUE TITLE
Slider thumbnails are overlapping offerboxes

### ISSUE THREAD

**Issue by MeiSign** [neeedo/neeedo-webapp#32]
If you scroll through the recent offers on the dashboard there are some thumbnails that are overlapping their offer divs.

![screen shot 2015-07-26 at 09 38 57](https://cloud.githubusercontent.com/assets/3068473/8892973/486badf0-337a-11e5-8631-df23582c603d.png)

**Comment by sasfeld** [comment]
Did a more-ore-less dirty bugfix for that (setting style on reloaded items directly solved the problem) and also fixed duplicate items in all sliders.

**Comment by sasfeld** [comment]
closed by c6496a385f4dd0163754d3391157448a39989f4f

**Comment by MeiSign** [comment]
Not fixed yet:
![screen shot 2015-07-26 at 19 52 56](https://cloud.githubusercontent.com/assets/3068473/8895143/d10a40cc-33cf-11e5-8abe-c9bae936e6b0.png)
