### ISSUE TITLE
Dashboard Map Popups

### ISSUE THREAD

**Issue by MeiSign** [neeedo/neeedo-webapp#36]
The Popups on the map are  most of the times to excessive.
I would suggest to mage the images in the popups smaller or add them in the text flow.
Pictures on the left side, text on the right side
![screen shot 2015-07-26 at 13 04 20](https://cloud.githubusercontent.com/assets/3068473/8893594/cbef2352-3396-11e5-8231-ac9844091496.png)

**Comment by sasfeld** [comment]
A bit late, but I will see what I can do.
