### ISSUE TITLE
Wrong message icon when resizing the window on matching page

### ISSUE THREAD

**Issue by MeiSign** [neeedo/neeedo-webapp#37]
When I resize the window on the matching page the message icon is replaced with the new messages icon even if I dont have any new messages. This only happens on the page when I resize the windwo:

![screen shot 2015-07-26 at 13 36 48](https://cloud.githubusercontent.com/assets/3068473/8893690/72d5912a-339b-11e5-9cb6-b78684b9970a.png)
![screen shot 2015-07-26 at 13 38 47](https://cloud.githubusercontent.com/assets/3068473/8893691/8043f798-339b-11e5-83ae-2d2f9aab1d03.png)

**Comment by Cneubauern** [comment]
solved by 9057887
