### ISSUE TITLE
Add missing German translations

### ISSUE THREAD

**Issue by GammaG** [neeedo/neeedo-webapp#4]
In Your Vicinity, 
as well as the button texts are english - language settings is german

**Comment by sasfeld** [comment]
more specific:

add missing translations - we will do this together with you mobile guys today :)

**Comment by GammaG** [comment]
they DO exist, one has to click on "de" again to see the german version. Does not work from scratch that's the point

**Comment by sasfeld** [comment]
no, that's not the point (it just can't be because i18n works if language header is given): we have to work on our translations.
